<div class="px-6 py-16 lg:px-8 max-w-[100vw]"><div class="mx-auto max-w-3xl text-base leading-7 text-neutral-700 dark:text-neutral-300"><h1 class="mt-16 text-3xl font-bold tracking-tight text-neutral-900 dark:text-neutral-100 sm:text-4xl">Svleek</h1>
<p class="mt-6 leading-8">This is the documentation/demo for Svleek. Svleek is a minimal, beautiful, and fast documentation generator. It is designed to be easy to use and to be able to generate beautiful documentation in seconds.</p>
<p class="mt-6 leading-8">This is a work in progress, and is not ready for production use.</p>
<h2 class="mt-16 text-2xl font-bold tracking-tight text-neutral-900 dark:text-neutral-100">Use</h2>
<p class="mt-6 leading-8">Currently the only way to use Svleek is to clone the repository, copy your docs into the <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">docs/</code> folder, then run the following commands:</p>
<div class="relative"><pre class="rounded-xl bg-neutral-100 dark:bg-neutral-900 p-4 mt-6 relative overflow-x-scroll" onclick="navigator.clipboard.writeText(this.querySelector(&quot;code&quot;).textContent.trim())"><code class="language-bash">npm install
npm run build
</code></pre><button class="absolute top-2 right-2 text-xs text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-300">Copy</button></div>
<p class="mt-6 leading-8">The documentation will be generated in the <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">build</code> folder. You can also run this command to preview it:</p>
<div class="relative"><pre class="rounded-xl bg-neutral-100 dark:bg-neutral-900 p-4 mt-6 relative overflow-x-scroll" onclick="navigator.clipboard.writeText(this.querySelector(&quot;code&quot;).textContent.trim())"><code class="language-bash">npm run preview
</code></pre><button class="absolute top-2 right-2 text-xs text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-300">Copy</button></div>
<h2 class="mt-16 text-2xl font-bold tracking-tight text-neutral-900 dark:text-neutral-100">Folder structure</h2>
<p class="mt-6 leading-8">All markdown files in the <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">docs/</code> folder will be parsed and converted to HTML. Subfolders are also supported and will become subpages (one level down only). Files that are not markdown files will be ignored (but will be copied to the static folder and can be linked/inlined in markdown files, e.g. <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">docs/selfie.png</code> can be inlined like this: <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">![this is me](/selfie.png)</code>).</p>
<p class="mt-6 leading-8">Markdown files and folders are sorted alphabetically, you can prefix them with numbers to change the order. If you name a file <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">00-test.md</code> it's actual name will be <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">test.md</code> but it will be before files that start with <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">01-</code> and so on.</p>
<h2 class="mt-16 text-2xl font-bold tracking-tight text-neutral-900 dark:text-neutral-100">Config</h2>
<p class="mt-6 leading-8">Create a <code class="rounded-md bg-neutral-200 dark:bg-neutral-800 p-1">svleek.config.json</code> file in your docs folder to configure Svleek. The following options are available:</p>
<div class="relative"><pre class="rounded-xl bg-neutral-100 dark:bg-neutral-900 p-4 mt-6 relative overflow-x-scroll" onclick="navigator.clipboard.writeText(this.querySelector(&quot;code&quot;).textContent.trim())"><code class="language-json"><span class="hljs-punctuation">&#123;</span>
	<span class="hljs-attr">"title"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"Svleek"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// sets the title of the main page</span>
	<span class="hljs-attr">"subtitle"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"Minimal, Beautiful, and Fast Documentation"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// sets the subtitle of the main page</span>
	<span class="hljs-attr">"image"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"/screenshot.png"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// sets the image of the main page</span>
	<span class="hljs-attr">"first_page"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"/docs/introduction"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// where the button on the main page should link to</span>
	<span class="hljs-attr">"button_label"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"Read the docs!"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// the label of the button on the main page</span>
	<span class="hljs-attr">"github"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"https://github.com"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// the link to the github repo of the project</span>
	<span class="hljs-attr">"accent"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"sky"</span> <span class="hljs-comment">// one of the tailwind colors</span>
<span class="hljs-punctuation">&#125;</span>
</code></pre><button class="absolute top-2 right-2 text-xs text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-300">Copy</button></div>
<p class="mt-6 leading-8">See <a href="https://tailwindcss.com/docs/customizing-colors#default-color-palette" class="font-semibold text-accent-600 hover:text-accent-500 dark:text-accent-500 dark:hover:text-accent-400">here</a> for a list of all available colors.</p>
<p class="mt-6 leading-8">You can also add a logo.svg file to the docs folder that will be used on the main page, in the navbar and as the favicon.</p>
</div></div>